spring:
  profiles:
    active: local

  application:
    name: bank-account-query

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./target/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true

logging.level:
  ch.keepcalm: DEBUG

axon:
  axonserver:
    servers: axonserver:8124

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
          %clr([${spring.zipkin.service.name:${spring.application.name:-}},){magenta}%clr(%X{X-B3-TraceId:-},){yellow}%clr(%X{X-B3-SpanId:-},){cyan}%clr(,%X{X-Span-Export:-}]){blue}%clr([%8.15t]){cyan}
          %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m
          ){faint}%n"


---
spring:
  config:
    activate:
      on-profile: local

axon:
  axonserver:
    servers: localhost:8124

server:
  port: 8081
