---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axonserver
  labels:
      app: axonserver
spec:
  serviceName: axonserver
  replicas: 1
  selector:
    matchLabels:
      app: axonserver
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
        - name: axonserver
#          image: axoniq/axonserver
          image: c3smonkey/axonserver-openshift:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8124
              protocol: TCP
            - name: gui
              containerPort: 8024
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8024
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          env:
            - name: AXONSERVER_HOSTNAME
              value: axonserver
          volumeMounts:
            - name: axon-data
              mountPath: /opt/axonserver/data
  volumeClaimTemplates:
    - metadata:
        name: axon-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver-gui
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
  selector:
    app: axonserver
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  ports:
    - name: grpc
      port: 8124
      targetPort: 8124
  selector:
    app: axonserver



# Routing
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: axonserver-gui
  name: axonserver-gui
spec:
#  host: axonserver-gui.apps.c3smonkey.ch
  port:
    targetPort: gui
  to:
    kind: Service
    name: axonserver-gui
    weight: 100

